### ISSUE TITLE
Go panic - cgo pointer error

### ISSUE THREAD

**Issue by aspann** [mutschler/mt#1]
Just want to give your tool a try, but it panics on execution with the following error:

```
INFO[0000] useing font: DroidSans.ttf
INFO[0000] generating contact sheet for test.mp4
WARN[0000] very small timestamps in use... consider decreasing numcaps 
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
panic(0x7ca0a0, 0xc820013580)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/mutschler/mt/Godeps/_workspace/src/github.com/opennota/screengen.(*Generator).ImageWxH(0xc8200f20c0, 0x2ad8, 0x780, 0x330, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/mutschler/mt/Godeps/_workspace/src/github.com/opennota/screengen/screengen.go:212 +0x137b
github.com/mutschler/mt/Godeps/_workspace/src/github.com/opennota/screengen.(*Generator).Image(0xc8200f20c0, 0x2ad8, 0x0, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/mutschler/mt/Godeps/_workspace/src/github.com/opennota/screengen/screengen.go:140 +0x55
main.GenerateScreenshots(0x7fff246ca43c, 0x8, 0x0, 0x0, 0x0)
	/opt/go/src/github.com/mutschler/mt/mt.go:133 +0x70d
main.main()
	/opt/go/src/github.com/mutschler/mt/mt.go:716 +0x360b
```

go version is: _go version go1.6.1 linux/amd64_

**Comment by aspann** [comment]
Hey, 

I managed it myself. With go 1.6 it is needed to run "mt" with:
GODEBUG=cgocheck=0 ...

so the command now looks like:
`$ GODEBUG=cgocheck=0 mt <options> <filename>`

But I think this issue should be fixed in the next release.

**Comment by mutschler** [comment]
thanks, seems like one of the dependencies im using got a problem there. i've opened an issue and submitted a PR already. If it's fixed im gonna push out a new version.

**Comment by aspann** [comment]
@mutschler, you're welcome.
im looking forward on this project, it seems to be one of the last "active" and shell based media thumbnailers. :+1:

I've build a small shell-script (http://dpaste.com/2Q29N88) wich uses imagemagick and your mt to generates a *.vtt file. Of course, the header and padding is disabled in the mt_config.json.

Maybe you can provide this functionality natively.

**Comment by mutschler** [comment]
@aspann i've pushed out a new version which hopefully should work with go 1.6 without `GODEBUG=cgocheck=0` being set. feedback is appreciated :)

if i understood the purpose of the *.vtt file correctly it's used by some html5 players to give you some sort of preview images? do you have any example/more info on that? looks interesting might be something for the next release ;)

for now my thoughts on this one are:

- provide a --vtt flag 
- said flag will disable --header --padding and --header-meta and generate a vtt file like this:

```
WEBVTT

00:00:00.000 --> 00:01:04.000
test.jpg#xywh=0,0,400,225

00:01:04.000 --> 00:02:09.000
test.jpg#xywh=400,0,400,225

00:02:09.000 --> 00:03:14.000
test.jpg#xywh=0,225,400,225

00:03:14.000 --> 00:04:19.000
test.jpg#xywh=400,225,400,225
```

**Comment by mutschler** [comment]
@aspann I've got some time and played around a little... seems like i've got what you where asking for :D with the latest commit (https://github.com/mutschler/mt/commit/c7e8340c014f326744af53f9c2513d8a7b76b005) it should now be possible to create `*.vtt` files when running with `--vtt` (maybe i should rename that to something more clear) as i said above, `--vtt` disables `--header`, `--header-meta` and `--padding`, the last one might not be needed but just to be sure :)

I've created a new pre-release so you could test... feedback would be appreciated ;)
