### ISSUE TITLE
How to use this without installing go?

### ISSUE THREAD

**Issue by muuvmuuv** [mutschler/mt#12]
Is it possible to build it to a single executable and attach it to a GitHub release? I don't have go or would likely use it in the future therefore I'm not interested in installing it on my System (macOS), but would really like to use this tool!

**Comment by mutschler** [comment]
There are binary files attachted to some releases which can be found here: https://github.com/mutschler/mt/releases there are however no releases for macOS currently so you would have to build it yourself.
