### ISSUE TITLE
panic: runtime error: integer divide by zero (mt.go:129)

### ISSUE THREAD

**Issue by ploober** [mutschler/mt#14]
I was getting this error. By debugging and stepping through I found that it was a result of the file and configuration, I think some input validation could be used to provide a better error message or warning to the user.

**This error happens when the `interval` is set to longer than the length of the video.** The logic on `mt.go:124` sets `numcaps` to 0. For example, when you have an `interval` of 60 and a video that is 41 seconds.

**Comment by mutschler** [comment]
actually that's pretty straigt forward to catch, however im not sure what to do in such a case... i'm thinking about:

check that the given `interval` is higher than the video duration if not throw an error and quit the app OR throw a warning and set the `interval` to the duration of the video.

personally i'd go with the first approach

**Comment by ploober** [comment]
I think the first approach sounds good. Just anything that conveys the nature of the problem to the user is fine. It was likely a mistake on the user's part to end up in this situation anyway so throwing an error seems appropriate. The issue isn't that it's throwing an error, it's that it isn't clear to the user why the error is being thrown or what to do to fix it.

Feel free to address it or I can contribute a PR when I have time.
