### ISSUE TITLE
Not accurate screenshots when using --interval

### ISSUE THREAD

**Issue by vladd49** [mutschler/mt#19]
Hi, 

When generating thumbnails for long videos (15 minutes and more) using --interval option time position where each thumbnail is generated is floating away from the place it should be. For example, I try to generate thumbnails every 10 seconds for a big video:

mt --font-size=8 --width=200 --webvtt=true --interval=10  sred21.mp4
...
INFO[0000] generating screenshot 01/216 at 00:00:10     
INFO[0000] generating screenshot 02/216 at 00:00:20     
INFO[0000] generating screenshot 03/216 at 00:00:30     
...
INFO[0022] generating screenshot 76/216 at 00:12:40     
INFO[0022] generating screenshot 77/216 at 00:12:51     
INFO[0023] generating screenshot 78/216 at 00:13:01     
...
INFO[0051] generating screenshot 153/216 at 00:25:31
INFO[0051] generating screenshot 154/216 at 00:25:42
INFO[0052] generating screenshot 155/216 at 00:25:52

You see that positions are corresponding to 10 second interval at first, but after 00:12:40 next screenshot is generated at 00:12:51, and after 00:25:31 another second is added making next screenshot at 00:25:42.

This behavior makes precise positioning of educational videos in html5 player impossible. Is there any way to fix this or to make a workaround?

**Comment by mutschler** [comment]
you are right. This is because of how interval currently works:
Interval only divides the playtime by interval and generates x screenshots afterwards, that should be fixed!

I've made a quick fix and pushed an update, could you please verify that it works for you as it should? 

Personally i've tested it with an 31 Minutes and 40 Minutes file and all looked good
Im using the same timestamps as you in your log ;)
```
INFO[0000] generating screenshot 01/186 at 00:00:10
INFO[0000] generating screenshot 02/186 at 00:00:20
INFO[0000] generating screenshot 03/186 at 00:00:30
...
INFO[0005] generating screenshot 76/186 at 00:12:40
INFO[0005] generating screenshot 77/186 at 00:12:50
INFO[0005] generating screenshot 78/186 at 00:13:00
...
INFO[0010] generating screenshot 153/186 at 00:25:30
INFO[0010] generating screenshot 154/186 at 00:25:40
INFO[0010] generating screenshot 155/186 at 00:25:50
```

**Comment by vladd49** [comment]
Looks to be fixed now, thank you. 

Btw it'd be nice to have a feature to limit the number of thumbnail images per one jpeg file and split it to several files. So for big videos and short thumbnail interval a single jpeg file won't grow too large. This can be done now by running mt several times with different --from and --to params and then combining the results in a single VTT file.

**Comment by mutschler** [comment]
thanks for the feedback!

regarding the feature you mentioned: you could make a small bash script which solves that issue i might think about adding this once i've got time to start migrating all the code for library usage
