### ISSUE TITLE
WebVTT: The Web Video Text Tracks Format

### ISSUE THREAD

**Issue by aspann** [mutschler/mt#2]
@mutschler I've tested the 1.0.6-dev version, there are some warnings during the compile process:

```
$ GOPATH=/opt/go GODEBUG=cgocheck=0 go get
$ GOPATH=/opt/go GODEBUG=cgocheck=0 go build
# github.com/mutschler/mt/Godeps/_workspace/src/github.com/opennota/screengen
/opt/go/src/github.com/mutschler/mt/Godeps/_workspace/src/github.com/opennota/screengen/screengen.go: In Funktion »av_read_frame_wrapper«:
/opt/go/src/github.com/mutschler/mt/Godeps/_workspace/src/github.com/opennota/screengen/screengen.go:42:3: Warnung: »priv« is deprecated (declared at /usr/include/libavcodec/avcodec.h:1446) [-Wdeprecated-declarations]
 //  pkt->priv = NULL; // zero uninitialized memory (see https://github.com/golang/go/issues/14426)
   ^
```

My ffmpeg version:
```
$ ffmpeg -version
ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 4.9.3 (Gentoo 4.9.3 p1.5, pie-0.6.4)
```

When mt is compiled without the GODEBUG flag the cgo pointer issue (https://github.com/mutschler/mt/issues/1) persists. Otherwise it's working like expected. The vtt file generation works like charm. 
(tested with JWPlayer and nginx + lua - automatically generated before streaming if not exists)

_[edit]_
The informations about the WebVTT format can be found here: https://w3c.github.io/webvtt/

Great work so far, you made my day! ;)

**Comment by mutschler** [comment]
@aspann the warning is intended to be shown and can be ignored, it's just to catch compatibility with ffmpeg 3.0... basically you get a warning that a deprecated function is used in ffmpeg 2.x to prevent memory leaks.

sadly i'm not able to reproduce the cgo pointer issue mentioned in #1 on my system. do you get them with the binary releases too?

Thanks for the feedback on vtt creation, i'm glad it works as expected :) still not sure about renaming the `--vtt` flag to `--webvtt` or something like that if you have any thoughts on that go ahead and let me know.

**Comment by aspann** [comment]
@mutschler as a gentoo user I'm always compiling from source.. :D 
- but for you I'll test the binary-release this evening and report my experience here.

The flag `--webvtt` should be fine. ;)

**Comment by aspann** [comment]
@mutschler sorry for my late reply. We had a barbecue yesterday evening, so i was not able to test it.. :D
Never use beer and root together.. ;)

But now i've just tested the binary-build (arm-hardfp and amd64) from you. Both worked like expected. Maybe you should remove the path (/home/cy....) from the archives and IMHO it would be better using a tar.gz or tar.bz2 for the linux releases (not everyone has unzip installed).

I think when those things are fixed, you can release it as version 1.0.6.

Great work! :+1:

**Comment by mutschler** [comment]
@aspann don't worry, barbecue is way more important than providing some feedback here ;)
Thanks for the hint about the path... seems like i totally forgot about that. and changing archives to tar.gz is also a nice idea... don't know why i changed it to zip in the first place :D

Again, thanks for testing and your feedback, i'll update the flag, change the archive type and remove the path and then i'll release `1.0.6` hopefully this weekend :)

**Comment by mutschler** [comment]
got some time and pushed out a new release, binaries are currently building

**Comment by aspann** [comment]
@mutschler great! :+1:
