### ISSUE TITLE
How do I create a static binary?

### ISSUE THREAD

**Issue by felipe19930** [mutschler/mt#20]
I noticed that the [1.0.8 release](https://github.com/mutschler/mt/releases/tag/1.0.8) was statically compiled, right?

Anyway, I'm trying to compile mt into a static binary as well, but I'm having issues and I don't know much about Go to even attempt to fix it:

```
$ env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go get github.com/mutschler/mt
# github.com/mutschler/mt
go/src/github.com/mutschler/mt/mt.go:76:14: undefined: screengen.NewGenerator
go/src/github.com/mutschler/mt/mt.go:488:14: undefined: screengen.NewGenerator
```

[This is the guide](https://oddcode.daveamit.com/2018/08/16/statically-compile-golang-binary/#linkingstatically) I followed.

Any help is appreciated.
Thanks.

**Comment by mutschler** [comment]
yeah all previous releases where statically linked. 
If i remember correctly the command i used was:

```
cd $GOPATH/github.com/mutschler/mt
go build --ldflags '-extldflags "-static -Wl,--allow-multiple-definition"'
```

If you don't want to cross compile it you could skip the `GOARCH` and `GOOS` flags, for cross compiling however you need those as well as `CGO_ENABLED=1` and a cross compiled version of ffmpeg for windows i did something like this:

cross compile ffmpeg for target:
```
TC_DIR="$HOME/cross/toolchains/x86_64-w64-mingw32/bin"
TC_PREFIX="x86_64-w64-mingw32"
cd $HOME/cross/source/ffmpeg
./configure --disable-programs --disable-asm --prefix=$HOME/cross/build/$TC_PREFIX/ffmpeg/ --disable-doc --enable-cross-compile --target-os=mingw32 --arch=i686 --cross-prefix=$TC_DIR/$TC_PREFIX- --pkg-config=pkg-config
make
make install
```

corss comile mt for target:
```
cd $GOPATH/src/github.com/mutschler/mt/ 
CC="$TC_DIR/$TC_PREFIX-gcc" LD="$TC_DIR/$TC_PREFIX-ld" CCFLAGS="-Wl,--allow-multiple-definition" CGO_CFLAGS="-Wl,--allow-multiple-definition" PKG_CONFIG_LIBDIR=$HOME/cross/build/$TC_PREFIX/ffmpeg/lib/pkgconfig/ LD_LIBRARY_PATH=$HOME/cross/build/$TC_PREFIX/ffmpeg/lib/ GOOS=windows GOARCH=386 CGO_ENABLED=1 go build --ldflags '-extldflags "-static -Wl,--allow-multiple-definition"' -o $HOME/cross/build/mt/mt-$TC_PREFIX.exe

```

**Comment by felipe19930** [comment]
Thank you for responding!

I'm trying to compile for Linux only (Ubuntu 20.04 LTS), but I'm getting a LOT of errors when I try to compile with this command you've suggested:

```
$ go build --ldflags '-extldflags "-static -Wl,--allow-multiple-definition"'
```

result: https://gist.github.com/felipe19930/8376cf1f70fbb8e4f408bfc4f30249c0/raw/2d44fc16a4c4152044f4d0322a9e41c38b7e5354/mt.log

Non-static compilation is working just fine though :(

**Comment by mutschler** [comment]
That's strange which version of ffmpeg are you using?
I've attached a statically compiled version to the latest release here's what i've done:

Download and compile ffmpeg-4.1 
```
mkdir -p $HOME/cross/source
cd $HOME/cross/source
wget http://ffmpeg.org/releases/ffmpeg-4.1.tar.bz2 && tar xjf $HOME/cross/source/ffmpeg-4.1.tar.bz2
cd  $HOME/cross/source/ffmpeg-4.1
./configure --disable-doc --disable-programs --disable-asm --prefix=$HOME/cross/build/ffmpeg/ --pkg-config=pkg-config && make && make install
```

Compile mt
```
export GOPATH=/home/cross/go
go get github.com/mutschler/mt
cd $GOPATH/src/github.com/mutschler/mt
PKG_CONFIG_LIBDIR=$HOME/cross/build/ffmpeg/lib/pkgconfig/ LD_LIBRARY_PATH=$HOME/cross/build/ffmpeg/lib/ go build --ldflags '-extldflags "-static -Wl,--allow-multiple-definition"' -o $HOME/cross/build/mt-1.0.10-linux_amd64
```

the following warnings might show but can be ignored

```
 github.com/mutschler/mt/vendor/gitlab.com/opennota/screengen
vendor/gitlab.com/opennota/screengen/screengen.go: In function ‘_cgo_017b9c96f72b_Cfunc_av_register_all’:
vendor/gitlab.com/opennota/screengen/screengen.go:166:2: warning: ‘av_register_all’ is deprecated [-Wdeprecated-declarations]
   matrix = matrixCopy
  ^~~~~~~~~~~~~~~
In file included from vendor/gitlab.com/opennota/screengen/screengen.go:20:0:
/home/tvdb//cross/build//ffmpeg//include/libavformat/avformat.h:2043:6: note: declared here
 void av_register_all(void);
      ^~~~~~~~~~~~~~~
```

**Comment by felipe19930** [comment]
Thank you for the instructions.

But even with me following it step-by-step, I basically got the same weird long list of errors. So I'm giving up for now, since you already provided a static binary for the last release - Thank you for that!

Feel free to close this (if you want). :)
