### ISSUE TITLE
Padding between images

### ISSUE THREAD

**Issue by andersonluis87** [mutschler/mt#21]
Is there a particular reason for mt.exe to generate the JPG image with padding between the images? 
Sometimes it happens, sometimes not. Not sure if this depends on the windows version. 
I am running the 1.0.8 mt version.

**Comment by mutschler** [comment]
i don't have a windows machine to test this at the moment but by default a 10px padding is added around the images (https://github.com/mutschler/mt/blob/1.0.8/mt.go#L506) which can be turned off by either passing `--padding 0` as an argument,  using environment variable `MT_PADDING=0` or setting `paddgin: 0` in the config file in one of this directories: https://github.com/mutschler/mt/blob/1.0.8/mt.go#L668-L670

however passing it as an argument/env can be used for runtime overwrites of the config file...

**Comment by andersonluis87** [comment]
Thank you very much! 
I will try passing the argument.

**Comment by andersonluis87** [comment]
@mutschler, It worked! :heart:
