### ISSUE TITLE
font argument not correctly used

### ISSUE THREAD

**Issue by zjuchenyuan** [mutschler/mt#23]
I find that no matter what value I set to `-f` or `--font`, mt always pring `useing font: DroidSans.ttf`.

I'm not familiar with golang, could you please check whether this piece of code is correct?

https://github.com/mutschler/mt/blob/fb1803d0257fbc9e2773e4142fedc81492fe0d63/mt.go#L575-L576

Should we change it to `flag.Lookup("font")` ? Thanks

**Comment by mutschler** [comment]
use `--font-all=PATH`

**Comment by zjuchenyuan** [comment]
> use `--font-all=PATH`

unknown flag: --font-all
