### ISSUE TITLE
undefined: nude.IsImageNude

### ISSUE THREAD

**Issue by goodforever** [mutschler/mt#29]
./helpers.go:190:17: undefined: nude.IsImageNude
make: *** [all] Error 2

**Comment by srxr** [comment]
I try to install the `mt` got same error with Go 1.16, but Go 1.15 is ok, looks like [github.com/koyachi/go-nude](/koyachi/go-nude) do not support Go 1.16

cc @prologic

**Comment by prologic** [comment]
Hmmm?
