### ISSUE TITLE
missing images on mutschler.github.io/mt

### ISSUE THREAD

**Issue by aspann** [mutschler/mt#3]
@mutschler sorry, i've just found another "issue".. ;)

There is an image missing on http://mutschler.github.io/mt/ maybe you can check that..
And eventually you can provide a small description on that page which describes the WebVTT, maybe it will push your tool because i know many people looking for this functionality. 

Have a nice weekend!

**Comment by mutschler** [comment]
@aspann thanks!
Yeah was thinking about adding an WebVTT Example and Description too... maybe also add a few more examples of some other functionality's and settings... didn't really put my focus on the website in the past. But i should definitively enhance it!

**Comment by ploober** [comment]
I have been using the WebVTT functionality with Video.js. While not officially supporting WebVTT thumbnails, there are some plugins which support it. Of the several branches I was able to get [this one working with the latest Video.js](https://github.com/247GradLabs/videojs-vtt-thumbnails).
