### ISSUE TITLE
Add info about audio-track

### ISSUE THREAD

**Issue by Numenorean** [mutschler/mt#30]
All tools like this have this opportunity. Because it's important enough to see if video has an audio or not

**Comment by mutschler** [comment]
Audio Codec should be Asses to the Header with the `header_meta` Option enabled

**Comment by Numenorean** [comment]
it is not what i want. it shows audio codec even if video doesn't have any sound

**Comment by mutschler** [comment]
Well what do you want then?
If there IS an audio track the codec get's appended after the Video Codec, if there is no audio track there isn't any audio Codec shown

With Audio: 
`Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 / AAC (Advanced Audio Coding)`

Without Audio:
`Codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 /`
