### ISSUE TITLE
Unable to build, screengen issue?

### ISSUE THREAD

**Issue by AsanaWiosna** [mutschler/mt#32]
**Environment:**
Ubuntu 20.04.2 
go 1.16.4
ffmpeg 4.4 (built from source)

```
$ go get github.com/mutschler/mt
# gitlab.com/opennota/screengen
go/pkg/mod/gitlab.com/opennota/screengen@v0.0.0-20210313035852-1f554a814ee7/screengen.go:125:16: streams[i].codec undefined (type *_Ctype_struct_AVStream has no field or method codec)
go/pkg/mod/gitlab.com/opennota/screengen@v0.0.0-20210313035852-1f554a814ee7/screengen.go:127:23: streams[i].codec undefined (type *_Ctype_struct_AVStream has no field or method codec)
go/pkg/mod/gitlab.com/opennota/screengen@v0.0.0-20210313035852-1f554a814ee7/screengen.go:134:33: streams[vStreamIndex].codec undefined (type *_Ctype_struct_AVStream has no field or method codec)
go/pkg/mod/gitlab.com/opennota/screengen@v0.0.0-20210313035852-1f554a814ee7/screengen.go:152:34: streams[aStreamIndex].codec undefined (type *_Ctype_struct_AVStream has no field or method codec)
```

**Comment by AsanaWiosna** [comment]
Downgrading to **go 1.14.15** and **ffmpeg 3.4** seems to resolve this issue.

**Comment by AsanaWiosna** [comment]
Hmm, was briefly able to get it to compile as I mentioned before. But after changing around a whole bunch of settings trying to cross-compile a binary for Windows (which I was never able to figure out due to a completely different set of issues), I started running into this error when I went back to compile a Linux binary again:
```
$ go build github.com/mutschler/mt/
# github.com/mutschler/mt
./mt.go:80:14: undefined: screengen.NewGenerator
./mt.go:517:14: undefined: screengen.NewGenerator
```
Not sure what change I made that is causing this new error.

**Comment by mutschler** [comment]
i used *go1.14.6* and *ffmpeg 4.3.2* for building which worked pretty well, there already is an issue for using go modules instead of dep (which seems to be deprecated and might cause your issue on go1.16) here https://github.com/mutschler/mt/issues/31

**Comment by mutschler** [comment]
so i've pushed an update and added some releases as well, those where compiled with **go1.16.4** and **ffmpeg 4.1**
