### ISSUE TITLE
unknown flag: --filename

### ISSUE THREAD

**Issue by silaas** [mutschler/mt#33]
Hello @mutschler, I am using latest release version [1.0.11](https://github.com/mutschler/mt/releases/download/1.0.11/mt-1.0.11-linux_amd64.tar.gz) and used --filename flag as mentioned in the docs. I got `unknown flag --filename` error. I also had a look at options via `--help` and found that `--filename` flag is not there. Please, help me avoid this issue. Thank you in advance.

**Comment by mutschler** [comment]
@silaas `filename` is the name of the option for the config file, the command line equivalent would be `--output="{{.Path}}{{.Name}}.jpg"`

**Comment by silaas** [comment]
Oh..my bad. Thank you for your quick response @mutschler.
