### ISSUE TITLE
need some static build binary ...

### ISSUE THREAD

**Issue by wxlg1117** [mutschler/mt#46]
> # cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
# strings /lib64/libc.so.6 |grep GLIBC
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
...
# ./mt
./mt: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by ./mt)
./mt: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./mt)
./mt: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./mt)
./mt: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./mt)
./mt: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./mt)
./mt: /lib64/libm.so.6: version `GLIBC_2.35' not found (required by ./mt)
./mt: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./mt)
./mt: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./mt)

> # cat /etc/redhat-release
Rocky Linux release 8.10 (Green Obsidian)
# strings /lib64/libc.so.6 |grep GLIBC
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_2.28
...
# ./mt
./mt: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ./mt)
./mt: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./mt)
./mt: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./mt)
./mt: /lib64/libm.so.6: version `GLIBC_2.35' not found (required by ./mt)
./mt: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./mt)

> # cat /etc/redhat-release
Rocky Linux release 9.4 (Blue Onyx)
# strings /lib64/libc.so.6 |grep GLIBC
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_2.28
GLIBC_2.29
GLIBC_2.30
GLIBC_2.31
GLIBC_2.32
GLIBC_2.33
GLIBC_2.34
...
# ./mt
./mt: /lib64/libm.so.6: version `GLIBC_2.35' not found (required by ./mt)

**Comment by mutschler** [comment]
strange...
I dont have a redhat env to test this but never had any problems on running it on any other unix based OS iv'e tested it with.

you could build the binary yourself though ;)

**Comment by wxlg1117** [comment]
Obviously, this is because you have to rely on the glibc library, but the glibc libraries in the redhat family of linux are usually very conservative, and the versions of these libraries are old and not up-to-date.

So, how do I compile statically?

**Comment by mutschler** [comment]
you could just compile on the actual system you are targeting. if that's not an option you could try to add `--ldflags "-extldflags '-static -Wl,--allow-multiple-definition'"` to the go build command

maybe this will work https://www.mediafire.com/file/qonxdge2f904na8/mt-1.0.14-dirty--linux_amd64.zip/file (had to upload it somewhere else since github allows only 25MB)

**Comment by wxlg1117** [comment]
The architecture is wrong: it is arm64, not amd64; and I don't have an arm64 device to test if it works properly.
`
# file mt-1.0.14-dirty--linux_amd64
mt-1.0.14-dirty--linux_amd64: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=57affcd81a69e582114e8928c7d4811f418b9aae, for GNU/Linux 3.7.0, with debug_info, not stripped

`

**Comment by mutschler** [comment]
Sorry my fault, this should work: https://www.mediafire.com/file/4aa78gpn579m68c/mt-1.0.14--linux_amd64.zip/file

here's the output from the test system:

```
$ file mt-1.0.14--linux_amd64
mt-1.0.14--linux_amd64: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=cdae28e344d22aa863b5fa8c9e83bc0f49b1f6b4, for GNU/Linux 3.2.0, with debug_info, not stripped

$ ./mt-1.0.14--linux_amd64 --version
mt Version 1.0.14 () built on 2024-10-31_10:58:26_UTC

$ uname -a
Linux 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux
```

**Comment by wxlg1117** [comment]
```
# ./mt-1.0.14--linux_amd64 --numcaps=64  columns=16 /data/Downloads/Russias.Wild.Tiger.\(2022\).1080p.WEB-DL.Rus.Eng.\[sub.Eng\]-BLUEBIRD.mkv
INFO[0000] using font: DroidSans.ttf
INFO[0000] generating contact sheet for columns=16
FATA[0000] Error reading video file: can't open input stream
# whereis ffmpeg
ffmpeg: /usr/bin/ffmpeg /usr/share/ffmpeg /usr/share/man/man1/ffmpeg.1.gz

```
get a error! how to ?

**Comment by sergeevabc** [comment]
Windows OS in not supported, I guess?

**Comment by mutschler** [comment]
It is but you have to build it your own, currently there is no CI for windows builds

**Comment by sergeevabc** [comment]
Well, I tried, but something went wrong.

```console
$ go version
go version go1.23.6 windows/amd64

$ go install github.com/mutschler/mt@latest
go: downloading github.com/mutschler/mt v0.0.0-20241218183515-eb876cf18c09
go: downloading github.com/BurntSushi/freetype-go v0.0.0-20160129220410-b763ddbfe298
go: downloading github.com/disintegration/gift v0.0.0-20150417200635-5b044b74c0b1
go: downloading github.com/disintegration/imaging v0.0.0-20151003014424-546cb3c5137b
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/koyachi/go-nude v0.0.2-0.20150410134931-699a88f33605
go: downloading github.com/mitchellh/mapstructure v0.0.0-20150717051158-281073eb9eb0
go: downloading github.com/sirupsen/logrus v0.8.8-0.20151204141443-446d1c146faa
go: downloading github.com/spf13/pflag v0.0.0-20151013200643-08b1a584251b
go: downloading github.com/spf13/viper v0.0.0-20151110042204-e37b56e207dd
go: downloading gitlab.com/opennota/screengen v1.0.2
go: downloading golang.org/x/image v0.0.0-20150916112557-baddd3465a05
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading github.com/kr/pretty v0.2.1
go: downloading github.com/magiconair/properties v1.5.5-0.20151021204130-6ac0b95f4492
go: downloading github.com/spf13/cast v0.0.0-20150803163715-ee815aaf958c
go: downloading github.com/spf13/jwalterweatherman v0.0.0-20151106170057-c2aa07df5938
go: downloading gopkg.in/fsnotify.v1 v1.4.7
go: downloading gopkg.in/yaml.v2 v2.0.0-20151201162745-f7716cbe52ba
go: downloading github.com/kr/text v0.1.0
# github.com/mutschler/mt
..Users\Me\go\pkg\mod\github.com\mutschler\mt@v0.0.0-20241218183515-eb876cf18c09\mt.go:84:24: undefined: screengen.NewGenerator
..Users\Me\go\pkg\mod\github.com\mutschler\mt@v0.0.0-20241218183515-eb876cf18c09\mt.go:529:24: undefined: screengen.NewGenerator
```

**Comment by mutschler** [comment]
make sure you have the LD_LIBRARY_PATH and PKG_CONFIG_PATH variables set correctly to where ffmpeg is... it _might_ be necessary to build ffmpeg yourself though.

**Comment by mutschler** [comment]
@sergeevabc github won't let me upload it here so here you go: https://www.mediafire.com/file/5bactptk464ujii/mt-1.0.15-ffmpeg-6.0-x86_64-w64-mingw32.zip/file couldn't test since i don't have a windows machine at hand...

if that works i'm gonna upload a new artifact to the latest build :)

**Comment by sergeevabc** [comment]
Great, your build works quite fast even on hardware from 2010s with Windows 7 SP1.
Alas, the last screenshot is always dark/black. You should do something about that.

![Image](https://github.com/user-attachments/assets/be995759-4e44-404d-bcde-4cfc3f695a95)

![Image](https://github.com/user-attachments/assets/b9ea5aa7-e90c-4e67-9f8f-50ed192d8b9d)

**Comment by mutschler** [comment]
I'll look into the ldflags, thanks.

regarding the black screen at the end: 
that's actually expected behaviour since the number of caps are evenly distributed by default. If you however use a movie with credits it's common that those end with a black screen. there are several options available to get rid of those:

1. try using `--skip-credits` which will cut off the last 2 minutes and hopefully gets rid of the credits in most cases
2. use `--to` with the ending time you'd like ex: `--to=02:00:00` will use that for the last capture
3. `--skip-blank` with `--blank-threshold=X` will help with "blank" or really dark screens... but that is more for screens in between since mt tries to skip the screen up to 3 times with the next one (+1 sec)

i'd recommend to use a settings file where you set the defaults so you'll don't have to provide all flags all the time. you could use mt to save the settings given to it with `--save-config=PATH` the default locations are:

1. current directory if there is a file called `mt.json`
2. `/etc/mt/mt.json`
3. User Home Directory + `/.mt/mt.json`

**Comment by sergeevabc** [comment]
> Would you be willing to test this build as well…

It works, thank you.

> Regarding the black screen at the end…

`--skip-credits` helps indeed.
`--to` requires specifying a timestamp for each file, which is less convenient.
'--skip-blank` paired with `--blank-threshold=X` did not help with the last screenshot.

> I'd recommend to use a settings file…

Done.

``` console
$ mt.exe -c 3 -n 9 -w 300 --comment="" --skip-credits --save-config="mt.json"
... level=info msg="config file saved to: mt.json"
```

![Image](https://github.com/user-attachments/assets/49f21b36-3ef2-4871-8e3f-786fcdff12ad)

![Image](https://github.com/user-attachments/assets/ebc39db4-faa1-4dac-830b-a77bf4659ecb)

**Comment by mutschler** [comment]
Thanks for testing :)

i know what you mean about the more informative scenes... but i think that's kind of a "personal preference"... so maybe try some different settings... i tend to go with interval settings a lot of time to be more specific but that requires in fact some manual work every time

to get brigther screens you could try the skip-black option with a lower threshold but that will just look at general brightness... i played around with some different calculations, you could try `skip-blurry` with a threshold as well (which will basically run canny edge detection) or play with the `sfw` option (which tries to eliminate nudity by counting "human flesh pixels" ... but that's more of a "funny thing to try"

sad thing: i don't think there is anything that could be done automatically to get to what you want closer... 

I was thinking about something like face detection... and played around with some techs to find "interesting parts in images" but that didn't work like i wanted it to :( maybe i'll give it another go... that was a few years ago...

So blur detection is basically canny edge detection (convoltution matrix on the greyscale image and counting pixels) the threashold is the percentage of pixels which are allowed to be considered "blurry"

for blank its the same: 
every pixel above 200,200,200 and below 50,50,50 is considered "blank" and the threshold is percentage of allowed blank pixels

so 85 will allow 85% of pixels to be considered blank/blurry...

**Comment by mutschler** [comment]
Ok so there is [smartcrop](https://github.com/muesli/smartcrop/) which basically does edge detection, skin detection and some saturation detection on an image to determine the best possible crop area for an image (which might could be adopted by calculating a score for an image and then retake the cap if the score is below a threshold) there also is [pigo](https://github.com/esimov/pigo) which seems to be a pure go face detection library...

still im not sure about the faces thing, since not all video has faces in it and not every frame with a face is a good one... what would be great is to have some sort of aesthetic classification like [this](https://github.com/LAION-AI/aesthetic-predictor) but implementing that would be way over the top i guess
