### ISSUE TITLE
Problems with the "to" setting in the config

### ISSUE THREAD

**Issue by S-u-m-u-n** [mutschler/mt#47]
1) Contrary to what the README is saying, it seems that internally, the program expects this setting to be called **end** instead of **to**:
https://github.com/mutschler/mt/blob/434fa45ac95fd98ba58b55a726ebe85cf843fd56/README.md?plain=1#L64-L65
https://github.com/mutschler/mt/blob/434fa45ac95fd98ba58b55a726ebe85cf843fd56/mt.go#L99-L100

2) It should be possible to only set the **from** value and leave the **to**/**end** value empty. This would allow skipping a part in the beginning of the video. Currently, this gives the error "from cant be higher than to":
https://github.com/mutschler/mt/blob/434fa45ac95fd98ba58b55a726ebe85cf843fd56/mt.go#L102-L104
It might even make sense to allow negative values for the **to**/**end** value, meaning that some time at the end will be skipped.

<br />
Since these are rather small things, I might be able to make a PR with some improvements myself, despite minimal knowledge of Go.

**Comment by mutschler** [comment]
1. you are right internally it's called `end` but the flag is called `--to` when the config is generated through mt it handles that but i guess if you write the config file yourself that can lead to confusion... i guess the best option would be to register an alias with Viper so booth can be used in the config file.

2. from a quick look it does look like getting rid of that line should allow the usage of from without the need of to. Im not realkly sure why i did it that way back when i wrote that. 

2.2 i really like the idea of supporting negative values for the to flag so you could do something like `--to=-00:05:00` to get rid of the last five minutes. 

I've pushed some changes which should solve those issues

**Comment by mutschler** [comment]
for some reason the mac os build fails. since i don't have access to any mac device atm im not really sure why. but new linux release should be there :)
