### ISSUE TITLE
generate contactSheets recursive

### ISSUE THREAD

**Issue by ben-ba** [mutschler/mt#7]
Missing an option to generate contactSheets recursive.

At the moment i use your program in the following way:

1. generate list of videofiles; 

> find /path/to/videos -type f -exec file -i {} + | sed -n '/video/s/:[^:]\+$//p' > videolist.txt

2. generate an array to pass them as argument to mt;

> mapfile -t < videolist.txt

3. generate contactSheets

> ./mt-1.0.8-arm-linux-gnueabihf --config-file=settings-test.json "${MAPFILE[@]}"

**Comment by mutschler** [comment]
why not call mt directly in exec?

`find /path/to/videos -type f -exec ./mt-1.0.8-arm-linux-gnueabihf --config-file=settings-test.json {}\;`

works as well (and is exactly what i am doing for recursive generation) and will generate a contact sheet for every valid file, that'll also fix #8
