### ISSUE TITLE
Skip on FatalErros

### ISSUE THREAD

**Issue by ben-ba** [mutschler/mt#8]
When i use your program with multiple arguments/files, after a fatal error it breaks.
Would be better if it continue and report the fatal error at the end or in an logfile.

**Comment by mutschler** [comment]
Fatal errors are designed to `exit` the app after the error is shown. so logging and continuing isn't really an option here... I might just lower the level from fatal to error, which would do exactly as you'd like: print a message/error and continue but that'll require a bit of work and i'm not really sure if that's what i want to do as it currently should only exit when:

1. Video File isn't a valid video file
2. the image for some reason can't be saved 

i see that that might be a problem when passing multiple files at once... so maybe i'll have to think about something to fix that...
