### ISSUE TITLE
Rotated videos do not produce rotated thumbs

### ISSUE THREAD

**Issue by pksml** [mutschler/mt#9]
Hi mutschler. I am using your program and really like its feature set. I find that my rotated videos do not produce rotated thumbnails. My video is in portrait mode where the height is greater than the length. Using ffprobe, my video shows this:

```
[SIDE_DATA]
side_data_type=Display Matrix
displaymatrix=
00000000:            0       65536           0
00000001:       -65536           0           0
00000002:     70778880           0  1073741824

rotation=-90
[/SIDE_DATA]
```

Would you be able to add support for rotated videos? It would be incredibly helpful. Thanks for all your great work!

**Comment by mutschler** [comment]
Hi, sorry it took me a while to come back to this issue... somehow i didn't get any notifications and missed it through my vacation... 

anyway i've pushed an update which should solve your problem.
